name: Deployment on Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on render
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_ID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_KEY }}" \
            -H "Accept: application/json" \
            -d '{}'