name: Deployment on Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on render
        run: |
          curl -X POST \
            "https://api.render.com/deploy/srv-${{ secrets.RENDER_ID }}" \
            -H "Authorization: Bearer ${{ secrets.RENDER_KEY }}" \
            -H "Accept: application/json"